CREATE TABLE user (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    tel VARCHAR(255) NOT NULL
    email VARCHAR(255) NOT NULL,
    balance INT UNSIGNED DEFAULT 0,
    password VARCHAR(255) NOT NULL,
    terms BOOLEAN NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY(id)
)

CREATE TABLE user_service (
user_id INT UNSIGNED NOT NULL,
service_id INT UNSIGNED NOT NULL,
PRIMARY KEY (user_id, service_id),
CONSTRAINT fk_user
    FOREIGN KEY(user_id)
    REFERENCES user(id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
CONSTRAINT fk_service
    FOREIGN KEY(service_id)
    REFERENCES service(id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
)